MONGODB_HOST: mongodb-{{ env }}.akhilkumarshop.online
REDIS_HOST: redis-{{ env }}.akhilkumarshop.online
MYSQL_HOST: mysql-{{ env }}.akhilkumarshop.online
RABBITMQ_HOST: rabbitmq-{{ env }}.akhilkumarshop.online
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.akhilkumarshop.online
USER_HOST: user.backend-alb-{{ env }}.akhilkumarshop.online
CART_HOST: cart.backend-alb-{{ env }}.akhilkumarshop.online
SHIPPING_HOST: shipping.backend-alb-{{ env }}.akhilkumarshop.online
PAYMENT_HOST: payment.backend-alb-{{ env }}.akhilkumarshop.online
